// 由 tools/jp_learner/gen_data.py 从 tools/jp_learner/jp_content.py 生成，请勿手改。

#include "jp_data.h"

const char *const JP_KANA_GROUP_NAMES[JP_KANA_GROUP_COUNT] = {
    "清音",
    "浊音",
    "半浊音",
    "拗音",
};

const char *const JP_WORD_CATEGORY_NAMES[JP_WORD_CATEGORY_COUNT] = {
    "问候",
    "数字",
    "时间",
    "人物",
    "饮食",
    "场所",
    "物品",
    "自然",
    "身体",
    "动词",
    "形容",
    "颜色",
    "方位",
};

// 假名卡片：平假名/片假名共用读音与发音片段（voice = 表内下标）。
const jp_kana_t JP_KANA[JP_KANA_COUNT] = {
    { .hira = "あ", .kata = "ア", .romaji = "a", .hira_row = "あ行", .kata_row = "ア行", .group = 0, .voice = 0 },
    { .hira = "い", .kata = "イ", .romaji = "i", .hira_row = "あ行", .kata_row = "ア行", .group = 0, .voice = 1 },
    { .hira = "う", .kata = "ウ", .romaji = "u", .hira_row = "あ行", .kata_row = "ア行", .group = 0, .voice = 2 },
    { .hira = "え", .kata = "エ", .romaji = "e", .hira_row = "あ行", .kata_row = "ア行", .group = 0, .voice = 3 },
    { .hira = "お", .kata = "オ", .romaji = "o", .hira_row = "あ行", .kata_row = "ア行", .group = 0, .voice = 4 },
    { .hira = "か", .kata = "カ", .romaji = "ka", .hira_row = "か行", .kata_row = "カ行", .group = 0, .voice = 5 },
    { .hira = "き", .kata = "キ", .romaji = "ki", .hira_row = "か行", .kata_row = "カ行", .group = 0, .voice = 6 },
    { .hira = "く", .kata = "ク", .romaji = "ku", .hira_row = "か行", .kata_row = "カ行", .group = 0, .voice = 7 },
    { .hira = "け", .kata = "ケ", .romaji = "ke", .hira_row = "か行", .kata_row = "カ行", .group = 0, .voice = 8 },
    { .hira = "こ", .kata = "コ", .romaji = "ko", .hira_row = "か行", .kata_row = "カ行", .group = 0, .voice = 9 },
    { .hira = "さ", .kata = "サ", .romaji = "sa", .hira_row = "さ行", .kata_row = "サ行", .group = 0, .voice = 10 },
    { .hira = "し", .kata = "シ", .romaji = "shi", .hira_row = "さ行", .kata_row = "サ行", .group = 0, .voice = 11 },
    { .hira = "す", .kata = "ス", .romaji = "su", .hira_row = "さ行", .kata_row = "サ行", .group = 0, .voice = 12 },
    { .hira = "せ", .kata = "セ", .romaji = "se", .hira_row = "さ行", .kata_row = "サ行", .group = 0, .voice = 13 },
    { .hira = "そ", .kata = "ソ", .romaji = "so", .hira_row = "さ行", .kata_row = "サ行", .group = 0, .voice = 14 },
    { .hira = "た", .kata = "タ", .romaji = "ta", .hira_row = "た行", .kata_row = "タ行", .group = 0, .voice = 15 },
    { .hira = "ち", .kata = "チ", .romaji = "chi", .hira_row = "た行", .kata_row = "タ行", .group = 0, .voice = 16 },
    { .hira = "つ", .kata = "ツ", .romaji = "tsu", .hira_row = "た行", .kata_row = "タ行", .group = 0, .voice = 17 },
    { .hira = "て", .kata = "テ", .romaji = "te", .hira_row = "た行", .kata_row = "タ行", .group = 0, .voice = 18 },
    { .hira = "と", .kata = "ト", .romaji = "to", .hira_row = "た行", .kata_row = "タ行", .group = 0, .voice = 19 },
    { .hira = "な", .kata = "ナ", .romaji = "na", .hira_row = "な行", .kata_row = "ナ行", .group = 0, .voice = 20 },
    { .hira = "に", .kata = "ニ", .romaji = "ni", .hira_row = "な行", .kata_row = "ナ行", .group = 0, .voice = 21 },
    { .hira = "ぬ", .kata = "ヌ", .romaji = "nu", .hira_row = "な行", .kata_row = "ナ行", .group = 0, .voice = 22 },
    { .hira = "ね", .kata = "ネ", .romaji = "ne", .hira_row = "な行", .kata_row = "ナ行", .group = 0, .voice = 23 },
    { .hira = "の", .kata = "ノ", .romaji = "no", .hira_row = "な行", .kata_row = "ナ行", .group = 0, .voice = 24 },
    { .hira = "は", .kata = "ハ", .romaji = "ha", .hira_row = "は行", .kata_row = "ハ行", .group = 0, .voice = 25 },
    { .hira = "ひ", .kata = "ヒ", .romaji = "hi", .hira_row = "は行", .kata_row = "ハ行", .group = 0, .voice = 26 },
    { .hira = "ふ", .kata = "フ", .romaji = "fu", .hira_row = "は行", .kata_row = "ハ行", .group = 0, .voice = 27 },
    { .hira = "へ", .kata = "ヘ", .romaji = "he", .hira_row = "は行", .kata_row = "ハ行", .group = 0, .voice = 28 },
    { .hira = "ほ", .kata = "ホ", .romaji = "ho", .hira_row = "は行", .kata_row = "ハ行", .group = 0, .voice = 29 },
    { .hira = "ま", .kata = "マ", .romaji = "ma", .hira_row = "ま行", .kata_row = "マ行", .group = 0, .voice = 30 },
    { .hira = "み", .kata = "ミ", .romaji = "mi", .hira_row = "ま行", .kata_row = "マ行", .group = 0, .voice = 31 },
    { .hira = "む", .kata = "ム", .romaji = "mu", .hira_row = "ま行", .kata_row = "マ行", .group = 0, .voice = 32 },
    { .hira = "め", .kata = "メ", .romaji = "me", .hira_row = "ま行", .kata_row = "マ行", .group = 0, .voice = 33 },
    { .hira = "も", .kata = "モ", .romaji = "mo", .hira_row = "ま行", .kata_row = "マ行", .group = 0, .voice = 34 },
    { .hira = "や", .kata = "ヤ", .romaji = "ya", .hira_row = "や行", .kata_row = "ヤ行", .group = 0, .voice = 35 },
    { .hira = "ゆ", .kata = "ユ", .romaji = "yu", .hira_row = "や行", .kata_row = "ヤ行", .group = 0, .voice = 36 },
    { .hira = "よ", .kata = "ヨ", .romaji = "yo", .hira_row = "や行", .kata_row = "ヤ行", .group = 0, .voice = 37 },
    { .hira = "ら", .kata = "ラ", .romaji = "ra", .hira_row = "ら行", .kata_row = "ラ行", .group = 0, .voice = 38 },
    { .hira = "り", .kata = "リ", .romaji = "ri", .hira_row = "ら行", .kata_row = "ラ行", .group = 0, .voice = 39 },
    { .hira = "る", .kata = "ル", .romaji = "ru", .hira_row = "ら行", .kata_row = "ラ行", .group = 0, .voice = 40 },
    { .hira = "れ", .kata = "レ", .romaji = "re", .hira_row = "ら行", .kata_row = "ラ行", .group = 0, .voice = 41 },
    { .hira = "ろ", .kata = "ロ", .romaji = "ro", .hira_row = "ら行", .kata_row = "ラ行", .group = 0, .voice = 42 },
    { .hira = "わ", .kata = "ワ", .romaji = "wa", .hira_row = "わ行", .kata_row = "ワ行", .group = 0, .voice = 43 },
    { .hira = "を", .kata = "ヲ", .romaji = "wo", .hira_row = "わ行", .kata_row = "ワ行", .group = 0, .voice = 44 },
    { .hira = "ん", .kata = "ン", .romaji = "n", .hira_row = "拨音", .kata_row = "拨音", .group = 0, .voice = 45 },
    { .hira = "が", .kata = "ガ", .romaji = "ga", .hira_row = "が行", .kata_row = "ガ行", .group = 1, .voice = 46 },
    { .hira = "ぎ", .kata = "ギ", .romaji = "gi", .hira_row = "が行", .kata_row = "ガ行", .group = 1, .voice = 47 },
    { .hira = "ぐ", .kata = "グ", .romaji = "gu", .hira_row = "が行", .kata_row = "ガ行", .group = 1, .voice = 48 },
    { .hira = "げ", .kata = "ゲ", .romaji = "ge", .hira_row = "が行", .kata_row = "ガ行", .group = 1, .voice = 49 },
    { .hira = "ご", .kata = "ゴ", .romaji = "go", .hira_row = "が行", .kata_row = "ガ行", .group = 1, .voice = 50 },
    { .hira = "ざ", .kata = "ザ", .romaji = "za", .hira_row = "ざ行", .kata_row = "ザ行", .group = 1, .voice = 51 },
    { .hira = "じ", .kata = "ジ", .romaji = "ji", .hira_row = "ざ行", .kata_row = "ザ行", .group = 1, .voice = 52 },
    { .hira = "ず", .kata = "ズ", .romaji = "zu", .hira_row = "ざ行", .kata_row = "ザ行", .group = 1, .voice = 53 },
    { .hira = "ぜ", .kata = "ゼ", .romaji = "ze", .hira_row = "ざ行", .kata_row = "ザ行", .group = 1, .voice = 54 },
    { .hira = "ぞ", .kata = "ゾ", .romaji = "zo", .hira_row = "ざ行", .kata_row = "ザ行", .group = 1, .voice = 55 },
    { .hira = "だ", .kata = "ダ", .romaji = "da", .hira_row = "だ行", .kata_row = "ダ行", .group = 1, .voice = 56 },
    { .hira = "ぢ", .kata = "ヂ", .romaji = "ji", .hira_row = "だ行", .kata_row = "ダ行", .group = 1, .voice = 57 },
    { .hira = "づ", .kata = "ヅ", .romaji = "zu", .hira_row = "だ行", .kata_row = "ダ行", .group = 1, .voice = 58 },
    { .hira = "で", .kata = "デ", .romaji = "de", .hira_row = "だ行", .kata_row = "ダ行", .group = 1, .voice = 59 },
    { .hira = "ど", .kata = "ド", .romaji = "do", .hira_row = "だ行", .kata_row = "ダ行", .group = 1, .voice = 60 },
    { .hira = "ば", .kata = "バ", .romaji = "ba", .hira_row = "ば行", .kata_row = "バ行", .group = 1, .voice = 61 },
    { .hira = "び", .kata = "ビ", .romaji = "bi", .hira_row = "ば行", .kata_row = "バ行", .group = 1, .voice = 62 },
    { .hira = "ぶ", .kata = "ブ", .romaji = "bu", .hira_row = "ば行", .kata_row = "バ行", .group = 1, .voice = 63 },
    { .hira = "べ", .kata = "ベ", .romaji = "be", .hira_row = "ば行", .kata_row = "バ行", .group = 1, .voice = 64 },
    { .hira = "ぼ", .kata = "ボ", .romaji = "bo", .hira_row = "ば行", .kata_row = "バ行", .group = 1, .voice = 65 },
    { .hira = "ぱ", .kata = "パ", .romaji = "pa", .hira_row = "ぱ行", .kata_row = "パ行", .group = 2, .voice = 66 },
    { .hira = "ぴ", .kata = "ピ", .romaji = "pi", .hira_row = "ぱ行", .kata_row = "パ行", .group = 2, .voice = 67 },
    { .hira = "ぷ", .kata = "プ", .romaji = "pu", .hira_row = "ぱ行", .kata_row = "パ行", .group = 2, .voice = 68 },
    { .hira = "ぺ", .kata = "ペ", .romaji = "pe", .hira_row = "ぱ行", .kata_row = "パ行", .group = 2, .voice = 69 },
    { .hira = "ぽ", .kata = "ポ", .romaji = "po", .hira_row = "ぱ行", .kata_row = "パ行", .group = 2, .voice = 70 },
    { .hira = "きゃ", .kata = "キャ", .romaji = "kya", .hira_row = "きゃ行", .kata_row = "キャ行", .group = 3, .voice = 71 },
    { .hira = "きゅ", .kata = "キュ", .romaji = "kyu", .hira_row = "きゃ行", .kata_row = "キャ行", .group = 3, .voice = 72 },
    { .hira = "きょ", .kata = "キョ", .romaji = "kyo", .hira_row = "きゃ行", .kata_row = "キャ行", .group = 3, .voice = 73 },
    { .hira = "しゃ", .kata = "シャ", .romaji = "sha", .hira_row = "しゃ行", .kata_row = "シャ行", .group = 3, .voice = 74 },
    { .hira = "しゅ", .kata = "シュ", .romaji = "shu", .hira_row = "しゃ行", .kata_row = "シャ行", .group = 3, .voice = 75 },
    { .hira = "しょ", .kata = "ショ", .romaji = "sho", .hira_row = "しゃ行", .kata_row = "シャ行", .group = 3, .voice = 76 },
    { .hira = "ちゃ", .kata = "チャ", .romaji = "cha", .hira_row = "ちゃ行", .kata_row = "チャ行", .group = 3, .voice = 77 },
    { .hira = "ちゅ", .kata = "チュ", .romaji = "chu", .hira_row = "ちゃ行", .kata_row = "チャ行", .group = 3, .voice = 78 },
    { .hira = "ちょ", .kata = "チョ", .romaji = "cho", .hira_row = "ちゃ行", .kata_row = "チャ行", .group = 3, .voice = 79 },
    { .hira = "にゃ", .kata = "ニャ", .romaji = "nya", .hira_row = "にゃ行", .kata_row = "ニャ行", .group = 3, .voice = 80 },
    { .hira = "にゅ", .kata = "ニュ", .romaji = "nyu", .hira_row = "にゃ行", .kata_row = "ニャ行", .group = 3, .voice = 81 },
    { .hira = "にょ", .kata = "ニョ", .romaji = "nyo", .hira_row = "にゃ行", .kata_row = "ニャ行", .group = 3, .voice = 82 },
    { .hira = "ひゃ", .kata = "ヒャ", .romaji = "hya", .hira_row = "ひゃ行", .kata_row = "ヒャ行", .group = 3, .voice = 83 },
    { .hira = "ひゅ", .kata = "ヒュ", .romaji = "hyu", .hira_row = "ひゃ行", .kata_row = "ヒャ行", .group = 3, .voice = 84 },
    { .hira = "ひょ", .kata = "ヒョ", .romaji = "hyo", .hira_row = "ひゃ行", .kata_row = "ヒャ行", .group = 3, .voice = 85 },
    { .hira = "みゃ", .kata = "ミャ", .romaji = "mya", .hira_row = "みゃ行", .kata_row = "ミャ行", .group = 3, .voice = 86 },
    { .hira = "みゅ", .kata = "ミュ", .romaji = "myu", .hira_row = "みゃ行", .kata_row = "ミャ行", .group = 3, .voice = 87 },
    { .hira = "みょ", .kata = "ミョ", .romaji = "myo", .hira_row = "みゃ行", .kata_row = "ミャ行", .group = 3, .voice = 88 },
    { .hira = "りゃ", .kata = "リャ", .romaji = "rya", .hira_row = "りゃ行", .kata_row = "リャ行", .group = 3, .voice = 89 },
    { .hira = "りゅ", .kata = "リュ", .romaji = "ryu", .hira_row = "りゃ行", .kata_row = "リャ行", .group = 3, .voice = 90 },
    { .hira = "りょ", .kata = "リョ", .romaji = "ryo", .hira_row = "りゃ行", .kata_row = "リャ行", .group = 3, .voice = 91 },
    { .hira = "ぎゃ", .kata = "ギャ", .romaji = "gya", .hira_row = "ぎゃ行", .kata_row = "ギャ行", .group = 3, .voice = 92 },
    { .hira = "ぎゅ", .kata = "ギュ", .romaji = "gyu", .hira_row = "ぎゃ行", .kata_row = "ギャ行", .group = 3, .voice = 93 },
    { .hira = "ぎょ", .kata = "ギョ", .romaji = "gyo", .hira_row = "ぎゃ行", .kata_row = "ギャ行", .group = 3, .voice = 94 },
    { .hira = "じゃ", .kata = "ジャ", .romaji = "ja", .hira_row = "じゃ行", .kata_row = "ジャ行", .group = 3, .voice = 95 },
    { .hira = "じゅ", .kata = "ジュ", .romaji = "ju", .hira_row = "じゃ行", .kata_row = "ジャ行", .group = 3, .voice = 96 },
    { .hira = "じょ", .kata = "ジョ", .romaji = "jo", .hira_row = "じゃ行", .kata_row = "ジャ行", .group = 3, .voice = 97 },
    { .hira = "びゃ", .kata = "ビャ", .romaji = "bya", .hira_row = "びゃ行", .kata_row = "ビャ行", .group = 3, .voice = 98 },
    { .hira = "びゅ", .kata = "ビュ", .romaji = "byu", .hira_row = "びゃ行", .kata_row = "ビャ行", .group = 3, .voice = 99 },
    { .hira = "びょ", .kata = "ビョ", .romaji = "byo", .hira_row = "びゃ行", .kata_row = "ビャ行", .group = 3, .voice = 100 },
    { .hira = "ぴゃ", .kata = "ピャ", .romaji = "pya", .hira_row = "ぴゃ行", .kata_row = "ピャ行", .group = 3, .voice = 101 },
    { .hira = "ぴゅ", .kata = "ピュ", .romaji = "pyu", .hira_row = "ぴゃ行", .kata_row = "ピャ行", .group = 3, .voice = 102 },
    { .hira = "ぴょ", .kata = "ピョ", .romaji = "pyo", .hira_row = "ぴゃ行", .kata_row = "ピャ行", .group = 3, .voice = 103 },
};

// 单词卡片：voice 从 JP_KANA_COUNT 开始连续编号。
const jp_word_t JP_WORDS[JP_WORD_COUNT] = {
    { .word = "こんにちは", .reading = "こんにちは", .romaji = "konnichiwa", .meaning = "你好", .category = 0, .voice = 104 },
    { .word = "おはよう", .reading = "おはよう", .romaji = "ohayou", .meaning = "早上好", .category = 0, .voice = 105 },
    { .word = "こんばんは", .reading = "こんばんは", .romaji = "konbanwa", .meaning = "晚上好", .category = 0, .voice = 106 },
    { .word = "ありがとう", .reading = "ありがとう", .romaji = "arigatou", .meaning = "谢谢", .category = 0, .voice = 107 },
    { .word = "すみません", .reading = "すみません", .romaji = "sumimasen", .meaning = "对不起；劳驾", .category = 0, .voice = 108 },
    { .word = "さようなら", .reading = "さようなら", .romaji = "sayounara", .meaning = "再见", .category = 0, .voice = 109 },
    { .word = "おやすみなさい", .reading = "おやすみなさい", .romaji = "oyasuminasai", .meaning = "晚安", .category = 0, .voice = 110 },
    { .word = "いただきます", .reading = "いただきます", .romaji = "itadakimasu", .meaning = "我开动了（饭前）", .category = 0, .voice = 111 },
    { .word = "ごちそうさま", .reading = "ごちそうさま", .romaji = "gochisousama", .meaning = "我吃好了（饭后）", .category = 0, .voice = 112 },
    { .word = "はい", .reading = "はい", .romaji = "hai", .meaning = "是；好的", .category = 0, .voice = 113 },
    { .word = "いいえ", .reading = "いいえ", .romaji = "iie", .meaning = "不；不是", .category = 0, .voice = 114 },
    { .word = "おねがいします", .reading = "おねがいします", .romaji = "onegaishimasu", .meaning = "拜托了", .category = 0, .voice = 115 },
    { .word = "一", .reading = "いち", .romaji = "ichi", .meaning = "一（1）", .category = 1, .voice = 116 },
    { .word = "二", .reading = "に", .romaji = "ni", .meaning = "二（2）", .category = 1, .voice = 117 },
    { .word = "三", .reading = "さん", .romaji = "san", .meaning = "三（3）", .category = 1, .voice = 118 },
    { .word = "四", .reading = "よん", .romaji = "yon", .meaning = "四（4）", .category = 1, .voice = 119 },
    { .word = "五", .reading = "ご", .romaji = "go", .meaning = "五（5）", .category = 1, .voice = 120 },
    { .word = "六", .reading = "ろく", .romaji = "roku", .meaning = "六（6）", .category = 1, .voice = 121 },
    { .word = "七", .reading = "なな", .romaji = "nana", .meaning = "七（7）", .category = 1, .voice = 122 },
    { .word = "八", .reading = "はち", .romaji = "hachi", .meaning = "八（8）", .category = 1, .voice = 123 },
    { .word = "九", .reading = "きゅう", .romaji = "kyuu", .meaning = "九（9）", .category = 1, .voice = 124 },
    { .word = "十", .reading = "じゅう", .romaji = "juu", .meaning = "十（10）", .category = 1, .voice = 125 },
    { .word = "百", .reading = "ひゃく", .romaji = "hyaku", .meaning = "一百", .category = 1, .voice = 126 },
    { .word = "千", .reading = "せん", .romaji = "sen", .meaning = "一千", .category = 1, .voice = 127 },
    { .word = "万", .reading = "まん", .romaji = "man", .meaning = "一万", .category = 1, .voice = 128 },
    { .word = "今日", .reading = "きょう", .romaji = "kyou", .meaning = "今天", .category = 2, .voice = 129 },
    { .word = "明日", .reading = "あした", .romaji = "ashita", .meaning = "明天", .category = 2, .voice = 130 },
    { .word = "昨日", .reading = "きのう", .romaji = "kinou", .meaning = "昨天", .category = 2, .voice = 131 },
    { .word = "今", .reading = "いま", .romaji = "ima", .meaning = "现在", .category = 2, .voice = 132 },
    { .word = "朝", .reading = "あさ", .romaji = "asa", .meaning = "早上", .category = 2, .voice = 133 },
    { .word = "昼", .reading = "ひる", .romaji = "hiru", .meaning = "中午；白天", .category = 2, .voice = 134 },
    { .word = "夜", .reading = "よる", .romaji = "yoru", .meaning = "晚上", .category = 2, .voice = 135 },
    { .word = "毎日", .reading = "まいにち", .romaji = "mainichi", .meaning = "每天", .category = 2, .voice = 136 },
    { .word = "時間", .reading = "じかん", .romaji = "jikan", .meaning = "时间", .category = 2, .voice = 137 },
    { .word = "今年", .reading = "ことし", .romaji = "kotoshi", .meaning = "今年", .category = 2, .voice = 138 },
    { .word = "午後", .reading = "ごご", .romaji = "gogo", .meaning = "下午", .category = 2, .voice = 139 },
    { .word = "私", .reading = "わたし", .romaji = "watashi", .meaning = "我", .category = 3, .voice = 140 },
    { .word = "人", .reading = "ひと", .romaji = "hito", .meaning = "人", .category = 3, .voice = 141 },
    { .word = "友達", .reading = "ともだち", .romaji = "tomodachi", .meaning = "朋友", .category = 3, .voice = 142 },
    { .word = "先生", .reading = "せんせい", .romaji = "sensei", .meaning = "老师", .category = 3, .voice = 143 },
    { .word = "学生", .reading = "がくせい", .romaji = "gakusei", .meaning = "学生", .category = 3, .voice = 144 },
    { .word = "父", .reading = "ちち", .romaji = "chichi", .meaning = "（我的）父亲", .category = 3, .voice = 145 },
    { .word = "母", .reading = "はは", .romaji = "haha", .meaning = "（我的）母亲", .category = 3, .voice = 146 },
    { .word = "兄", .reading = "あに", .romaji = "ani", .meaning = "（我的）哥哥", .category = 3, .voice = 147 },
    { .word = "姉", .reading = "あね", .romaji = "ane", .meaning = "（我的）姐姐", .category = 3, .voice = 148 },
    { .word = "弟", .reading = "おとうと", .romaji = "otouto", .meaning = "弟弟", .category = 3, .voice = 149 },
    { .word = "妹", .reading = "いもうと", .romaji = "imouto", .meaning = "妹妹", .category = 3, .voice = 150 },
    { .word = "子供", .reading = "こども", .romaji = "kodomo", .meaning = "孩子", .category = 3, .voice = 151 },
    { .word = "家族", .reading = "かぞく", .romaji = "kazoku", .meaning = "家人", .category = 3, .voice = 152 },
    { .word = "水", .reading = "みず", .romaji = "mizu", .meaning = "水", .category = 4, .voice = 153 },
    { .word = "お茶", .reading = "おちゃ", .romaji = "ocha", .meaning = "茶", .category = 4, .voice = 154 },
    { .word = "ご飯", .reading = "ごはん", .romaji = "gohan", .meaning = "米饭；饭", .category = 4, .voice = 155 },
    { .word = "パン", .reading = "パン", .romaji = "pan", .meaning = "面包", .category = 4, .voice = 156 },
    { .word = "肉", .reading = "にく", .romaji = "niku", .meaning = "肉", .category = 4, .voice = 157 },
    { .word = "魚", .reading = "さかな", .romaji = "sakana", .meaning = "鱼", .category = 4, .voice = 158 },
    { .word = "野菜", .reading = "やさい", .romaji = "yasai", .meaning = "蔬菜", .category = 4, .voice = 159 },
    { .word = "果物", .reading = "くだもの", .romaji = "kudamono", .meaning = "水果", .category = 4, .voice = 160 },
    { .word = "卵", .reading = "たまご", .romaji = "tamago", .meaning = "鸡蛋", .category = 4, .voice = 161 },
    { .word = "牛乳", .reading = "ぎゅうにゅう", .romaji = "gyuunyuu", .meaning = "牛奶", .category = 4, .voice = 162 },
    { .word = "コーヒー", .reading = "コーヒー", .romaji = "koohii", .meaning = "咖啡", .category = 4, .voice = 163 },
    { .word = "お酒", .reading = "おさけ", .romaji = "osake", .meaning = "酒", .category = 4, .voice = 164 },
    { .word = "家", .reading = "いえ", .romaji = "ie", .meaning = "家；房子", .category = 5, .voice = 165 },
    { .word = "学校", .reading = "がっこう", .romaji = "gakkou", .meaning = "学校", .category = 5, .voice = 166 },
    { .word = "駅", .reading = "えき", .romaji = "eki", .meaning = "车站", .category = 5, .voice = 167 },
    { .word = "店", .reading = "みせ", .romaji = "mise", .meaning = "商店", .category = 5, .voice = 168 },
    { .word = "病院", .reading = "びょういん", .romaji = "byouin", .meaning = "医院", .category = 5, .voice = 169 },
    { .word = "銀行", .reading = "ぎんこう", .romaji = "ginkou", .meaning = "银行", .category = 5, .voice = 170 },
    { .word = "会社", .reading = "かいしゃ", .romaji = "kaisha", .meaning = "公司", .category = 5, .voice = 171 },
    { .word = "部屋", .reading = "へや", .romaji = "heya", .meaning = "房间", .category = 5, .voice = 172 },
    { .word = "トイレ", .reading = "トイレ", .romaji = "toire", .meaning = "厕所", .category = 5, .voice = 173 },
    { .word = "国", .reading = "くに", .romaji = "kuni", .meaning = "国家", .category = 5, .voice = 174 },
    { .word = "町", .reading = "まち", .romaji = "machi", .meaning = "城镇", .category = 5, .voice = 175 },
    { .word = "公園", .reading = "こうえん", .romaji = "kouen", .meaning = "公园", .category = 5, .voice = 176 },
    { .word = "本", .reading = "ほん", .romaji = "hon", .meaning = "书", .category = 6, .voice = 177 },
    { .word = "車", .reading = "くるま", .romaji = "kuruma", .meaning = "汽车", .category = 6, .voice = 178 },
    { .word = "電話", .reading = "でんわ", .romaji = "denwa", .meaning = "电话", .category = 6, .voice = 179 },
    { .word = "時計", .reading = "とけい", .romaji = "tokei", .meaning = "钟表", .category = 6, .voice = 180 },
    { .word = "傘", .reading = "かさ", .romaji = "kasa", .meaning = "伞", .category = 6, .voice = 181 },
    { .word = "かばん", .reading = "かばん", .romaji = "kaban", .meaning = "包", .category = 6, .voice = 182 },
    { .word = "靴", .reading = "くつ", .romaji = "kutsu", .meaning = "鞋", .category = 6, .voice = 183 },
    { .word = "机", .reading = "つくえ", .romaji = "tsukue", .meaning = "桌子", .category = 6, .voice = 184 },
    { .word = "いす", .reading = "いす", .romaji = "isu", .meaning = "椅子", .category = 6, .voice = 185 },
    { .word = "窓", .reading = "まど", .romaji = "mado", .meaning = "窗户", .category = 6, .voice = 186 },
    { .word = "写真", .reading = "しゃしん", .romaji = "shashin", .meaning = "照片", .category = 6, .voice = 187 },
    { .word = "お金", .reading = "おかね", .romaji = "okane", .meaning = "钱", .category = 6, .voice = 188 },
    { .word = "山", .reading = "やま", .romaji = "yama", .meaning = "山", .category = 7, .voice = 189 },
    { .word = "川", .reading = "かわ", .romaji = "kawa", .meaning = "河", .category = 7, .voice = 190 },
    { .word = "海", .reading = "うみ", .romaji = "umi", .meaning = "海", .category = 7, .voice = 191 },
    { .word = "空", .reading = "そら", .romaji = "sora", .meaning = "天空", .category = 7, .voice = 192 },
    { .word = "雨", .reading = "あめ", .romaji = "ame", .meaning = "雨", .category = 7, .voice = 193 },
    { .word = "花", .reading = "はな", .romaji = "hana", .meaning = "花", .category = 7, .voice = 194 },
    { .word = "木", .reading = "き", .romaji = "ki", .meaning = "树", .category = 7, .voice = 195 },
    { .word = "犬", .reading = "いぬ", .romaji = "inu", .meaning = "狗", .category = 7, .voice = 196 },
    { .word = "猫", .reading = "ねこ", .romaji = "neko", .meaning = "猫", .category = 7, .voice = 197 },
    { .word = "鳥", .reading = "とり", .romaji = "tori", .meaning = "鸟", .category = 7, .voice = 198 },
    { .word = "天気", .reading = "てんき", .romaji = "tenki", .meaning = "天气", .category = 7, .voice = 199 },
    { .word = "目", .reading = "め", .romaji = "me", .meaning = "眼睛", .category = 8, .voice = 200 },
    { .word = "耳", .reading = "みみ", .romaji = "mimi", .meaning = "耳朵", .category = 8, .voice = 201 },
    { .word = "口", .reading = "くち", .romaji = "kuchi", .meaning = "嘴", .category = 8, .voice = 202 },
    { .word = "手", .reading = "て", .romaji = "te", .meaning = "手", .category = 8, .voice = 203 },
    { .word = "足", .reading = "あし", .romaji = "ashi", .meaning = "脚", .category = 8, .voice = 204 },
    { .word = "頭", .reading = "あたま", .romaji = "atama", .meaning = "头", .category = 8, .voice = 205 },
    { .word = "顔", .reading = "かお", .romaji = "kao", .meaning = "脸", .category = 8, .voice = 206 },
    { .word = "体", .reading = "からだ", .romaji = "karada", .meaning = "身体", .category = 8, .voice = 207 },
    { .word = "歯", .reading = "は", .romaji = "ha", .meaning = "牙齿", .category = 8, .voice = 208 },
    { .word = "行く", .reading = "いく", .romaji = "iku", .meaning = "去", .category = 9, .voice = 209 },
    { .word = "来る", .reading = "くる", .romaji = "kuru", .meaning = "来", .category = 9, .voice = 210 },
    { .word = "帰る", .reading = "かえる", .romaji = "kaeru", .meaning = "回去；回家", .category = 9, .voice = 211 },
    { .word = "食べる", .reading = "たべる", .romaji = "taberu", .meaning = "吃", .category = 9, .voice = 212 },
    { .word = "飲む", .reading = "のむ", .romaji = "nomu", .meaning = "喝", .category = 9, .voice = 213 },
    { .word = "見る", .reading = "みる", .romaji = "miru", .meaning = "看", .category = 9, .voice = 214 },
    { .word = "聞く", .reading = "きく", .romaji = "kiku", .meaning = "听；问", .category = 9, .voice = 215 },
    { .word = "読む", .reading = "よむ", .romaji = "yomu", .meaning = "读", .category = 9, .voice = 216 },
    { .word = "書く", .reading = "かく", .romaji = "kaku", .meaning = "写", .category = 9, .voice = 217 },
    { .word = "話す", .reading = "はなす", .romaji = "hanasu", .meaning = "说话", .category = 9, .voice = 218 },
    { .word = "買う", .reading = "かう", .romaji = "kau", .meaning = "买", .category = 9, .voice = 219 },
    { .word = "寝る", .reading = "ねる", .romaji = "neru", .meaning = "睡觉", .category = 9, .voice = 220 },
    { .word = "起きる", .reading = "おきる", .romaji = "okiru", .meaning = "起床", .category = 9, .voice = 221 },
    { .word = "分かる", .reading = "わかる", .romaji = "wakaru", .meaning = "明白", .category = 9, .voice = 222 },
    { .word = "待つ", .reading = "まつ", .romaji = "matsu", .meaning = "等待", .category = 9, .voice = 223 },
    { .word = "する", .reading = "する", .romaji = "suru", .meaning = "做", .category = 9, .voice = 224 },
    { .word = "大きい", .reading = "おおきい", .romaji = "ookii", .meaning = "大的", .category = 10, .voice = 225 },
    { .word = "小さい", .reading = "ちいさい", .romaji = "chiisai", .meaning = "小的", .category = 10, .voice = 226 },
    { .word = "新しい", .reading = "あたらしい", .romaji = "atarashii", .meaning = "新的", .category = 10, .voice = 227 },
    { .word = "古い", .reading = "ふるい", .romaji = "furui", .meaning = "旧的", .category = 10, .voice = 228 },
    { .word = "高い", .reading = "たかい", .romaji = "takai", .meaning = "高的；贵的", .category = 10, .voice = 229 },
    { .word = "安い", .reading = "やすい", .romaji = "yasui", .meaning = "便宜的", .category = 10, .voice = 230 },
    { .word = "暑い", .reading = "あつい", .romaji = "atsui", .meaning = "热的（天气）", .category = 10, .voice = 231 },
    { .word = "寒い", .reading = "さむい", .romaji = "samui", .meaning = "冷的（天气）", .category = 10, .voice = 232 },
    { .word = "おいしい", .reading = "おいしい", .romaji = "oishii", .meaning = "好吃的", .category = 10, .voice = 233 },
    { .word = "楽しい", .reading = "たのしい", .romaji = "tanoshii", .meaning = "快乐的", .category = 10, .voice = 234 },
    { .word = "忙しい", .reading = "いそがしい", .romaji = "isogashii", .meaning = "忙的", .category = 10, .voice = 235 },
    { .word = "好き", .reading = "すき", .romaji = "suki", .meaning = "喜欢", .category = 10, .voice = 236 },
    { .word = "元気", .reading = "げんき", .romaji = "genki", .meaning = "精神；健康", .category = 10, .voice = 237 },
    { .word = "静か", .reading = "しずか", .romaji = "shizuka", .meaning = "安静", .category = 10, .voice = 238 },
    { .word = "きれい", .reading = "きれい", .romaji = "kirei", .meaning = "漂亮；干净", .category = 10, .voice = 239 },
    { .word = "赤い", .reading = "あかい", .romaji = "akai", .meaning = "红色的", .category = 11, .voice = 240 },
    { .word = "青い", .reading = "あおい", .romaji = "aoi", .meaning = "蓝色的", .category = 11, .voice = 241 },
    { .word = "白い", .reading = "しろい", .romaji = "shiroi", .meaning = "白色的", .category = 11, .voice = 242 },
    { .word = "黒い", .reading = "くろい", .romaji = "kuroi", .meaning = "黑色的", .category = 11, .voice = 243 },
    { .word = "黄色い", .reading = "きいろい", .romaji = "kiiroi", .meaning = "黄色的", .category = 11, .voice = 244 },
    { .word = "何", .reading = "なに", .romaji = "nani", .meaning = "什么", .category = 12, .voice = 245 },
    { .word = "誰", .reading = "だれ", .romaji = "dare", .meaning = "谁", .category = 12, .voice = 246 },
    { .word = "どこ", .reading = "どこ", .romaji = "doko", .meaning = "哪里", .category = 12, .voice = 247 },
    { .word = "いつ", .reading = "いつ", .romaji = "itsu", .meaning = "什么时候", .category = 12, .voice = 248 },
    { .word = "いくら", .reading = "いくら", .romaji = "ikura", .meaning = "多少钱", .category = 12, .voice = 249 },
    { .word = "上", .reading = "うえ", .romaji = "ue", .meaning = "上面", .category = 12, .voice = 250 },
    { .word = "下", .reading = "した", .romaji = "shita", .meaning = "下面", .category = 12, .voice = 251 },
    { .word = "前", .reading = "まえ", .romaji = "mae", .meaning = "前面", .category = 12, .voice = 252 },
    { .word = "後ろ", .reading = "うしろ", .romaji = "ushiro", .meaning = "后面", .category = 12, .voice = 253 },
    { .word = "右", .reading = "みぎ", .romaji = "migi", .meaning = "右边", .category = 12, .voice = 254 },
    { .word = "左", .reading = "ひだり", .romaji = "hidari", .meaning = "左边", .category = 12, .voice = 255 },
    { .word = "中", .reading = "なか", .romaji = "naka", .meaning = "里面", .category = 12, .voice = 256 },
};
